#ifndef __DMA_H__
#define __DMA_H__

typedef enum 
{
	/* DMA Channel 1 Sources */
	DMA_CH1
	DMA_CH1_ADC1	= DMA_CH1,
	DMA_CH1_TIM2_CH3	= DMA_CH1,
	DMA_CH1_TIM4_CH1	= DMA_CH1,

	/* DMA Channel 2 Sources */
	DMA_CH2,
	DMA_CH2_SPI1_RX		= DMA_CH2,
	DMA_CH2_USART3_TX	= DMA_CH2,
	DMA_CH2_TIM1_CH1	= DMA_CH2,
	DMA_CH2_TIM2_UPDATE	= DMA_CH2,
	DMA_CH2_TIM3_CH3	= DMA_CH2,

	/* DMA Channel 3 Sources */
	DMA_CH3,
	DMA_CH3_SPI1_TX		= DMA_CH3,
	DMA_CH3_USART3_RX	= DMA_CH3,
	DMA_CH3_TIM1_CH2	= DMA_CH3,
	DMA_CH3_TIM3_CH4	= DMA_CH3, 
	DMA_CH3_TIM3_UPDATE	= DMA_CH3,

	/* DMA Channel 4 Sources */
	DMA_CH4,
	DMA_CH4_SPI2_RX		= DMA_CH4,
	DMA_CH4_USART1_TX	= DMA_CH4,
	DMA_CH4_I2C2_TX		= DMA_CH4,
	DMA_CH4_TIM1_CH4	= DMA_CH4,
	DMA_CH4_TIM1_TRIG	= DMA_CH4,
	DMA_CH4_TIM1_COM	= DMA_CH4,
	DMA_CH4_TIM4_CH2	= DMA_CH4,

	/* DMA Channel 5 Sources */
	DMA_CH5,
	DMA_CH5_SPI2_TX		= DMA_CH5,
	DMA_CH5_USART1_RX	= DMA_CH5,
	DMA_CH5_I2C2_RX		= DMA_CH5,
	DMA_CH5_TIM1_UPDATE	= DMA_CH5,
	DMA_CH5_TIM2_CH1	= DMA_CH5,
	DMA_CH5_TIM4_CH3	= DMA_CH5,

	/* DMA Channel 6 Sources */
	DMA_CH6,
	DMA_CH6_USART2_RX	= DMA_CH6,
	DMA_CH6_I2C1_TX		= DMA_CH6,
	DMA_CH6_TIM1_CH3	= DMA_CH6,
	DMA_CH6_TIM3_CH1	= DMA_CH6,
	DMA_CH6_TIM3_TRIG	= DMA_CH6,
	
	/* DMA Channel 7 Sources */
	DMA_CH7,
	DMA_CH7_USART2_TX	= DMA_CH7,
	DMA_CH7_I2C1_RX		= DMA_CH7,
	DMA_CH7_TIM2_CH2	= DMA_CH7,
	DMA_CH7_TIM2_CH4	= DMA_CH7,
	DMA_CH7_TIM4_UPDATE	= DMA_CH7
} DMA_CH_PERIPHERALS_t;

#endif /*__DMA_H__*/